id: P008263
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 13:12:03.146011
source_metadata:
  id: bdr:W1KG23262
  title: འགྲེལ་ཆུང་ཕྱོགས་བསྒྲིགས་སྐལ་བཟང་ཐར་ལམ་སྟོན་པའི་སྒྲོན་མེ།
  author: ''
  volumes:
    0a85a7c120394b19a88c3d0f45656e4c:
      image_group_id: I1KG23312
      title: ''
      volume_number: 1
      total_pages: 150
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
